const ingredientsData: string[] = [
  // Legumes
  'abóbora',
  'abobrinha',
  'alho',
  'alho-poró',
  'alcaparra',
  'alecrim',
  'anis',
  'aipo',
  'aipo-rábano',
  'aspargo',
  'batata-doce',
  'batata-inglesa',
  'beterraba',
  'brócolis',
  'cebola',
  'cebolinha',
  'cheiro-verde',
  'couve',
  'couve-flor',
  'chuchu',
  'ervilha',
  'feijão-de-vagem',
  'gengibre',
  'hortelã',
  'inhame',
  'jiló',
  'lentilha',
  'manjericão',
  'mandioca',
  'mostarda',
  'nabo',
  'napa',
  'pepino',
  'pimentão',
  'repolho',
  'rúcula',
  'salsão',
  'tomate',
  'tremoço',
  'vagem',
  'agrião',
  'azedinha',
  'beterraba-roxa',
  'caqui-manga',
  'cará',
  'cenoura',
  'couve-manteiga',
  'couve-rábano',
  'espinafre',
  'fava',
  'inhame-branco',
  'jilo-verde',
  'lentilha-vermelha',
  'maca peruana',
  'mandioquinha',
  'mostarda-branca',
  'nabo-da-china',
  'palmito',
  'pepino-curtido',
  'pimentão-verde',
  'repolho-roxo',
  'rúcula-de-áfrica',
  'salsão-cebolinha',
  'tomate-cereja',
  'tremoço-branco',
  'vagem-amarela',

  // Frutas
  'abacaxi',
  'acerola',
  'amora',
  'banana',
  'caqui',
  'coco',
  'figo',
  'goiaba',
  'graviola',
  'jaca',
  'laranja',
  'maçã',
  'manga',
  'melancia',
  'morango',
  'pera',
  'pêssego',
  'abacate',
  'ameixa',
  'cereja',
  'damasco',
  'figo seco',
  'groselha',
  'kiwi',
  'limão',
  'lima',
  'maçã verde',
  'maçã vermelha',
  'manga espada',
  'manga tommy',
  'maracujá',
  'melão',
  'melão-cantaloupe',
  'melão-de-são-caetano',
  'nectarina',
  'nêspera',
  'pera-abacate',
  'pera-asiática',
  'pera-dágua',
  'pera-rocha',
  'pêssego-amarelo',
  'pêssego-vermelho',
  'pina',
  'pitaya',
  'romã',
  'uva',
  'uva-italiana',
  'uva-passa',
  'uva-vermelha',
  'uva-rosa',
  'umbu',
  'vergamota',
  'vitamina',
  'xerém',
  'zimbro',

  // Cereais
  'arroz',
  'feijão',
  'macarrão',
  'pão',
  'trigo',
  'aveia',
  'milho',
  'centeio',
  'soja',
  'arroz integral',
  'quinoa',
  'amaranto',
  'chia',
  'couscous',
  'tapioca',
  'mandioca',
  'inhame',
  'arroz basmati',
  'arroz jasmine',
  'arroz negro',
  'arroz vermelho',
  'arroz integral moído',
  'arroz integral vaporizado',
  'arroz para sushi',
  'arroz para risoto',
  'arroz para paella',
  'feijão preto',
  'feijão branco',
  'feijão carioca',
  'feijão fradinho',
  'feijão preto-de-olho',
  'feijão vermelho',
  'feijão-de-corda',
  'feijão-preto-rajado',
  'feijão-branco-rajado',
  'feijão-carioca-rajado',
  'macarrão espaguete',
  'macarrão penne',
  'macarrão farfalle',
  'macarrão rigatoni',
  'macarrão fettuccine',
  'macarrão tortiglioni',
  'macarrão fusilli',
  'macarrão conchiglie',
  'macarrão rotini',
  'pão francês',
  'pão de forma',
  'pão integral',
  'pão de trigo',
  'pão de centeio',
  'pão de aveia',
  'pão de milho',
  'pão de soja',
  'trigo-sarraceno',
  'aveia em flocos',
  'aveia em flocos finos',
  'aveia em flocos grossos',
  'aveia em flocos sem glúten',
  'aveia instantânea',
  'aveia em flocos de ouro',
  'aveia em flocos de prata',
  'aveia em flocos de pérola',
  'milho em grão',
  'milho em lata',
  'milho-verde',
  'milho-pipoca',
  'centeio em grão',
  'centeio em flocos',
  'soja em grão',
  'soja em flocos',
  'soja em pó',

  // Laticínios
  'leite',
  'leite condensado',
  'creme de leite',
  'queijo fresco',
  'queijo mussarela',
  'queijo cheddar',
  'queijo parmesano',
  'queijo provolone',
  'queijo minas',
  'queijo parmesão',
  'queijo gorgonzola',
  'queijo brie',
  'queijo camembert',
  'queijo feta',
  'queijo ricota',
  'queijo cottage',
  'iogurte',
  'iogurte natural',
  'iogurte grego',
  'iogurte de frutas',
  'iogurte desnatado',
  'iogurte integral',
  'iogurte com zero lactose',
  'iogurte sem lactose',
  'manteiga',
  'manteiga sem sal',
  'manteiga com sal',
  'ghee',
  'nata',
  'sour cream',
  'creme azedo',
  'whey protein',
  'caseína',
  'lactose',
  'soro de leite',
  'soro de leite em pó',
  'leite em pó',
  'leite fermentado',
  'leite de vaca',
  'leite de búfala',
  'leite de cabra',
  'leite de soja',
  'leite de amêndoa',
  'leite de coco',
  'leite de arroz',
  'leite de aveia',
  'leite de quinoa',
  'leite de macadâmia',
  'leite de castanha-do-pará',
  'leite de pistache',
  'leite de ervilha',
  'leite de girassol',
  'leite de hemp',
  'leite de azeitona',

  // especiarias
  'açafrão',
  'açafrão-da-terra',
  'alho',
  'alho-poró',
  'alcaparra',
  'alecrim',
  'anis',
  'aniz-estrelado',
  'asafoetida',
  'baunilha',
  'boldo',
  'cebola',
  'cebolinha',
  'cardamomo',
  'caril',
  'casca de laranja',
  'casca de limão',
  'castanha-da-índia',
  'cavalinha',
  'cheiro-verde',
  'cidreira',
  'coentro',
  'cominho',
  'cravo',
  'curry',
  'damasco',
  'dente-de-leão',
  'dill',
  'erva-doce',
  'estragão',
  'gengibre',
  'hortelã',
  'jambu',
  'jóia',
  'lavanda',
  'louro',
  'macacão',
  'macis',
  'manjericão',
  'manjerona',
  'mostarda',
  'noz-moscada',
  'orégano',
  'pacoquinha',
  'pimenta-da-jamaica',
  'pimenta-do-reino',
  'pimenta-de-caiena',
  'pimenta-vermelha',
  'sal',
  'salsa',
  'sândalo',
  'tomilho',
  'trigo-sarraceno',
  'turmerique',
  'vinagre',
  'xerez',

  // outros
  'azeite',
  'óleo',
  'vinagre',
  'açúcar',
  'café',
  'chá',
  'água',
  'suco',
  'chocolate',
  'mel',
  'farinha',
  'massa',
  'biscoito',
  'bolo',
  'doce',
  'salgado',

  // carnes
  'carne de boi',
  'carne moída',
  'alcatra',
  'coxão duro',
  'coxão mole',
  'patinho',
  'miolo',
  'picanha',
  'fraldinha',
  'contrafilé',
  'lagarto',
  'mignon',
  'costela',
  'temperado',
  'carne de porco',
  'linguiça',
  'bacon',
  'pernil',
  'lombo',
  'costela',
  'panceta',
  'carne de frango',
  'sobrecoxa',
  'coxa',
  'peito',
  'asas',
  'filé de peito',
  'frango a passarinho',
  'isca de frango',
  'carne de peixe',
  'isca de peixe',
  'camarão',
  'lula',
  'meu-tudo-em-tudo',
  'empadão',
  'quibe',
  'pastel',
  'coxinha',
  'esfiha',
  'carne de jacaré',
  'carne de capivara',
  'carne de tatu',
  'carne de preguiça',
  'carne de cutia',
  'carne de veado',
  'carne de coelho',
  'carne de peru',
  'carne de pato',
  'carne de ganso',
  'carne de rã',
  'carne de lagosta',
  'carne de caranguejo',
  'carne de camarão',
  'carne de ostra',
  'carne de mexilhões',
  'carne de vieiras',
  'carne de polvo',
  'carne de lula',
  'carne de sardinha',
  'carne de atum',
  'carne de salmão',
  'carne de truta',
  'carne de bacalhau',
  'carne de cação',
  'carne de corvina',
  'carne de tainha',
  'carne de dourado',
  'carne de surubim',
  'carne de pirarucu',
  'carne de tambaqui',
  'carne de pintado',
  'carne de pacu',
  'carne de acará',
  'carne de piracanjuba',
  'carne de piapara',
  'carne de piauçu',
  'carne de pescada branca',
  'carne de pescada amarela',
  'carne de pescada dourada',
  'carne de pescada branca',
  'carne de pescada amarela',
  'carne de pescada dourada',

  'arroz',
  'água',
  'abacate',
  'abacaxi',
  'abóbora',
  'açafrão',
  'acelga',
  'açúcar',
  'agrião',
  'alcachofra',
  'alcaparra',
  'alface',
  'alho',
  'alho-poró',
  'almeirão',
  'amêndoa',
  'amendoim',
  'amora',
  'angu',
  'aveia',
  'avelã',
  'azeite',
  'azeitona',
  'uva',
  'uva-passa',
  'vagem',
  'valeriana',
  'vatapá',
  'vinho',
  'wasabi',
  'whisky',
  'xarope de bordo',
  'xerém',
  'xilitol',
  'zimbro',
  'zimbro em bagas',
  'zimbro moído',
  'zimbro fresco',
  'zimbro seco',
  'zabaione',
  'zaatar',
  'zest de limão',
  'zest de laranja',
  'zafrão',
  'batata',
  'banana',
  'beterraba',
  'broto de feijão',
  'caju',
  'cebola',
  'cogumelo',
  'couve',
  'feijão',
  'gengibre',
  'lentilha',
  'leite de vaca',
  'manga',
  'manteiga',
  'margarina',
  'pepino',
  'pão francês',
  'pão de forma',
  'pimentão',
  'salmão',
  'semente de girassol',
  'tofu',
  'tâmara',
  'trigo',
  'alfafa',
  'amarula',
  'aneto',
  'araruta',
  'mandioquinha',
  'beldroega',
  'caqui',
  'chicória',
  'damasco',
  'endívia',
  'figo',
  'goiaba',
  'hortelã',
  'jicama',
  'kiwis',
  'lichia',
  'manjericão',
  'Nabo',
  'papaya',
  'polvilho doce',
  'polvilho azedo',
  'quiuí',
  'rúcula',
  'salsaparrilha',
  'tapioca',
  'umeboshi',
  'amaranto',
  'agar-agar',
  'baru',
  'chuchu',
  'dill',
  'endro',
  'fubá',
  'gergelim',
  'hibisco',
  'inhame',
  'jabuticaba',
  'lavanda',
  'mandioquinha',
  'nirá',
  'ora-pro-nóbis',
  'pupunha',
  'quinoa',
  'rabanete',
  'sálvia',
  'alecrim',
  'alho',
  'almôndega',
  'avestruz',
  'bacon',
  'berinjela',
  'canela',
  'carne bovina',
  'carne de cordeiro',
  'carne de pato',
  'carne de porco',
  'carne moída',
  'carne suína',
  'cebolinha',
  'coelho',
  'coentro',
  'costela',
  'curry',
  'empanado de frango',
  'ervilha',
  'filé mignon',
  'frango',
  'galinha',
  'gergelim',
  'grão de bico',
  'louro',
  'macarrão',
  'maminha',
  'manjericão',
  'maracujá',
  'molho barbecue',
  'mostarda',
  'nuggets',
  'orégano',
  'ovo',
  'páprica',
  'picanha',
  'pimenta',
  'pimentão',
  'presunto',
  'queijo',
  'rúcula',
  'salsicha',
  'salsa',
  'salvia',
  'shiitake',
  'tofu',
  'tomilho',
  'truta',
  'vitela',
  'abobrinha',
  'alcatra',
  'alho-poró',
  'amêijoa',
  'atum',
  'badejo',
  'baunilha',
  'bife de chorizo',
  'bisteca suína',
  'caldo de galinha',
  'carne de búfalo',
  'carne de jacaré',
  'carne seca',
  'chouriço',
  'codorna',
  'cordeiro',
  'costeleta de cordeiro',
  'coxa de peru',
  'coxa de frango',
  'cravo-da-índia',
  'curry em pó',
  'endro',
  'escargot',
  'faisão',
  'farinha de rosca',
  'foie gras',
  'funcho',
  'gema de ovo',
  'gorgonzola',
  'haddock',
  'iscas de fígado',
  'ketchup',
  'lagosta',
  'laranja',
  'lombo de porco',
  'manjerona',
  'mariscos',
  'mexilhão',
  'mignon suíno',
  'mirtilo',
  'molho de soja',
  'músculo bovino',
  'ostra',
  'ovo de avestruz',
  'páprica defumada',
  'pargo',
  'pássaro',
  'pato',
  'peito de frango',
  'percebes',
  'perna de cordeiro',
  'porco',
  'pudim de carne',
  'rabanada',
  'rim de porco',
  'rins de vitela',
  'sal do Himalaia',
  'sal de cozinha',
  'salsão',
  'tomate',
  'salsicha alemã',
  'salmão defumado',
  'sêmola de trigo',
  'siri',
  'tainha',
  'tangerina',
  'toucinho',
  'truta salmonada',
  'tutano',
  'vitelo',
  'xerém de castanha',
];

export default ingredientsData;
